using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EgyptianeInvoicing.Core.Constants
{
    public static class ActivityTypes
    {
        private static readonly List<ActivityType> Codes = new List<ActivityType>
    {
        new ActivityType { Code = "0111", EnglishDescription = "Cultivation of grains and crops (except for rice), legumes and oilseeds", ArabicDescription = "زراعة الحبوب والمحاصيل ( فيما عدا الارز ) والبقوليات والحبوب الزيتية" },
        new ActivityType { Code = "0112", EnglishDescription = "Cultivation of rice", ArabicDescription = "زراعة الارز" },
        new ActivityType { Code = "0113", EnglishDescription = "Growing vegetables, melons, roots and tubers", ArabicDescription = "زراعة الخضر ؤالبطيخ والجذور والدرنات" },
        new ActivityType { Code = "0114", EnglishDescription = "Cultivation of sugar cane", ArabicDescription = "زراعة قصب السكر" },
        new ActivityType { Code = "0115", EnglishDescription = "Tobacco cultivation", ArabicDescription = "زراعة التبغ" },
        new ActivityType { Code = "0116", EnglishDescription = "Growing fiber crops", ArabicDescription = "زراعة المحاصيل ذات الالياف" },
        new ActivityType { Code = "0119", EnglishDescription = "Cultivation of other non-perennial crops", ArabicDescription = "زراعة المحاصيل غير المعمرة الاخرى" },
        new ActivityType { Code = "0121", EnglishDescription = "Cultivation of grapevines", ArabicDescription = "زراعة الكروم" },
        new ActivityType { Code = "0122", EnglishDescription = "Growing tropical and subtropical fruits", ArabicDescription = "زراعة الفواكه الاستوائية وشبه الاستوائية" },
        new ActivityType { Code = "0123", EnglishDescription = "Cultivation of citrus fruits", ArabicDescription = "زراعة الموالح" },
        new ActivityType { Code = "0124", EnglishDescription = "Cultivation of fruit with Date kernel and from palm trees", ArabicDescription = "زراعة الفواكة ذات النواة والناتجة عن انواع النخيل" },
        new ActivityType { Code = "0125", EnglishDescription = "Plant fruit trees and shrubs and other nuts", ArabicDescription = "زراعة أشجار وشجيرات الفواكهة والمكسرات الاخرى" },
        new ActivityType { Code = "0126", EnglishDescription = "Growing oil fruits", ArabicDescription = "زراعة الفواكهة الزيتية" },
        new ActivityType { Code = "0127", EnglishDescription = "Cultivation of the crops from which drinks are extracted", ArabicDescription = "زراعة المحاصيل التى تستخرج منها المشروبات" },
        new ActivityType { Code = "0128", EnglishDescription = "Cultivation of spice crops, aromatics, medicine and pharmaceutical drugs", ArabicDescription = "زراعة محاصيل التوابل والعطريات والادوية والعقاقير الصيدلانية" },
        new ActivityType { Code = "0129", EnglishDescription = "Cultivation of other perennial crops", ArabicDescription = "زراعة المحاصيل المعمرة الاخرى" },
        new ActivityType { Code = "0130", EnglishDescription = "Crop breeding", ArabicDescription = "تكاثر المحاصيل" },
        new ActivityType { Code = "0141", EnglishDescription = "Breeding of cattle and buffalo", ArabicDescription = "تربية الماشية والجواميس" },
        new ActivityType { Code = "0142", EnglishDescription = "Breeding of horses and mare", ArabicDescription = "تربية الخيول و الفرس" },
        new ActivityType { Code = "0143", EnglishDescription = "Breeding of camels", ArabicDescription = "تربية الجمال والهجن" },
        new ActivityType { Code = "0144", EnglishDescription = "Breeding sheep and goats", ArabicDescription = "تربية الخراف والماعز" },
        new ActivityType { Code = "0145", EnglishDescription = "Breeding of Pig", ArabicDescription = "تربية الحنازير" },
        new ActivityType { Code = "0146", EnglishDescription = "Poultry farming", ArabicDescription = "تربية الدواجن" },
        new ActivityType { Code = "0149", EnglishDescription = "Breeding other animals", ArabicDescription = "تربية الحيوانات الاخرى" },
        new ActivityType { Code = "0150", EnglishDescription = "Mixed education", ArabicDescription = "التربية المختلطة" },
        new ActivityType { Code = "0161", EnglishDescription = "Support activities for crop production", ArabicDescription = "الانشطة الداعمة لانتاج المحاصيل" },
        new ActivityType { Code = "0162", EnglishDescription = "Activities in support of animal production", ArabicDescription = "الانشطة الداعمة لانتاج الحيوانات" },
        new ActivityType { Code = "0163", EnglishDescription = "Post-harvest activities", ArabicDescription = "الانشطة اللاحقة لحصاد المحاصيل" },
        new ActivityType { Code = "0164", EnglishDescription = "Preparing grains for reproduction", ArabicDescription = "تجهيز الحبوب للتكاثر" },
        new ActivityType { Code = "0170", EnglishDescription = "Hunting, erection, and related service activities", ArabicDescription = "الصيد ونصب الاشراك وانشطة الخدمات ذات الصلة" },
        new ActivityType { Code = "0210", EnglishDescription = "Forest care and forest-related activities", ArabicDescription = "رعاية الغابات والانشطة المتصلة بالغابات" },
        new ActivityType { Code = "0220", EnglishDescription = "Wood cutting", ArabicDescription = "قطع الاخشاب" },
        new ActivityType { Code = "0230", EnglishDescription = "Assembling non-wood forest products", ArabicDescription = "تجميع المنتجات غير الخشبية بالغابات" },
        new ActivityType { Code = "0240", EnglishDescription = "Forest support services", ArabicDescription = "الخدمات الداعمة للغابات" },
        new ActivityType { Code = "0311", EnglishDescription = "Fishing", ArabicDescription = "الصيد البحرى" },
        new ActivityType { Code = "0312", EnglishDescription = "River fishing", ArabicDescription = "الصيد النهرى" },
        new ActivityType { Code = "0321", EnglishDescription = "Marine farms", ArabicDescription = "المزارع البحرية" },
        new ActivityType { Code = "0322", EnglishDescription = "River farms", ArabicDescription = "المزارع النهرية" },
        new ActivityType { Code = "0411", EnglishDescription = "Earn a job", ArabicDescription = "كسب عمل" },
        new ActivityType { Code = "0412", EnglishDescription = "Income from government agencies salaries", ArabicDescription = "ايرادات من مرتبات جهات حكوميه" },
        new ActivityType { Code = "0413", EnglishDescription = "Income and salaries from the public business sector", ArabicDescription = "إيرادات ومرتبات من قطاع الاعمال العام" },
        new ActivityType { Code = "0414", EnglishDescription = "Income and salaries from the private sector", ArabicDescription = "ايرادات ومرتبات من قطاع خاص" },
        new ActivityType { Code = "0415", EnglishDescription = "Income and salary from non-subject entities", ArabicDescription = "ايرادات ومرتبات من جهات غير خاضعه" },
        new ActivityType { Code = "0416", EnglishDescription = "Inspection and sting", ArabicDescription = "تفتيش ودمغة" },
        new ActivityType { Code = "0441", EnglishDescription = "Income of agricultural lands", ArabicDescription = "ايرادالاراضي الزراعيه" },
        new ActivityType { Code = "0442", EnglishDescription = "Revenue from constructed real estate", ArabicDescription = "ايراد العقارات المبنيه" },
        new ActivityType { Code = "0444", EnglishDescription = "Income of real estate activities", ArabicDescription = "ايراد الانشطه العقاريه" },
        new ActivityType { Code = "0451", EnglishDescription = "Errand stamp", ArabicDescription = "دمغة مأمورية" },
        new ActivityType { Code = "0461", EnglishDescription = "Revenue from non-funders", ArabicDescription = "ايرادات غير الممولين" },
        new ActivityType { Code = "0462", EnglishDescription = "Revenue of transferred capital", ArabicDescription = "إيراد رؤوس الأموال المنقولة" },
        new ActivityType { Code = "0463", EnglishDescription = "Income earned from abroad", ArabicDescription = "ايرادات محصله من الخارج" },
        new ActivityType { Code = "0464", EnglishDescription = "Other categories / miscellaneous other income", ArabicDescription = "فئات اخري/ ايرادات اخري متنوعه" },
        new ActivityType { Code = "0471", EnglishDescription = "Free market revenue", ArabicDescription = "ايرادات أسواق حرة" },
        new ActivityType { Code = "0472", EnglishDescription = "Free Zones revenue", ArabicDescription = "ايرادات مناطق حره" },
        new ActivityType { Code = "0510", EnglishDescription = "Hard coal mining", ArabicDescription = "تعدين الفحم الصلب" },
        new ActivityType { Code = "0520", EnglishDescription = "Lignite mining", ArabicDescription = "تعدين الليجنيت" },
        new ActivityType { Code = "0610", EnglishDescription = "Extract the crude oil", ArabicDescription = "استخرج البترول الخام" },
        new ActivityType { Code = "0620", EnglishDescription = "Extract natural gas", ArabicDescription = "استخرج االغاز الطبيعى" },
        new ActivityType { Code = "0710", EnglishDescription = "Iron ore mining", ArabicDescription = "تعدين الحديد الخام" },
        new ActivityType { Code = "0721", EnglishDescription = "Uranium and raw thorium mining", ArabicDescription = "تعدين اليورانيوم والثوريوم الخام" },
        new ActivityType { Code = "0729", EnglishDescription = "Mining other non-ferrous metals", ArabicDescription = "تعدين المعادن الخام الاخرى غير الحديدية" },
        new ActivityType { Code = "0810", EnglishDescription = "Quarrying to extract stones, sand and shale", ArabicDescription = "استغلال المحاجر لاستخراج الاحجار والرمال والطفل" },
        new ActivityType { Code = "0891", EnglishDescription = "Chemical minerals and fertilizer extraction", ArabicDescription = "استخراج المعادن الكيميائية والاسمدة" },
        new ActivityType { Code = "0892", EnglishDescription = "Peat extraction", ArabicDescription = "استخراج الخث" },
        new ActivityType { Code = "0893", EnglishDescription = "Salt extraction", ArabicDescription = "استخراج الملح" },
        new ActivityType { Code = "0899", EnglishDescription = "Other mining and quarrying activities are not elsewhere classified", ArabicDescription = "الانشطة الاخرى للتعدين واستغلال المحاجر غير مصنفة فى موضع اخر" },
        new ActivityType { Code = "0910", EnglishDescription = "Service activities in support of oil and natural gas extraction", ArabicDescription = "انشطة الخدمات الداعمة لاعمال استخراج البترول والغاز الطبيعى" },
        new ActivityType { Code = "0990", EnglishDescription = "Service activities in support of other mining and quarrying activities", ArabicDescription = "انشطة الخدمات الداعمة للاعمال الاخرى للتعدين واستغلال المحاجر" },
        new ActivityType { Code = "1010", EnglishDescription = "Meat processing and preservation", ArabicDescription = "تصنيع وحفظ اللحوم" },
        new ActivityType { Code = "1020", EnglishDescription = "Manufacture and preservation of fish, crustaceans and mollusks", ArabicDescription = "تصنيع وحفظ الاسماك والقشريات والرخويات" },
        new ActivityType { Code = "1030", EnglishDescription = "Manufacturing and preserving fruits and vegetables", ArabicDescription = "تصنيع وحفظ الفواكهة و الخضراوات" },
        new ActivityType { Code = "1040", EnglishDescription = "Manufacture of vegetable and animal oils and fats", ArabicDescription = "تصنيع الزيوت و الدهون الحيوانية والنباتية" },
        new ActivityType { Code = "1050", EnglishDescription = "Dairy products manufacturing", ArabicDescription = "تصنيع منتجات الالبان" },
        new ActivityType { Code = "1061", EnglishDescription = "Manufacture of grain mill products", ArabicDescription = "تصنيع منتجات طواحين الحبوب" },
        new ActivityType { Code = "1062", EnglishDescription = "Manufacture of starch and starch products", ArabicDescription = "تصنيع منتجات النشاء ومنتجات النشاء" },
        new ActivityType { Code = "1071", EnglishDescription = "Manufacturing bakery products", ArabicDescription = "تصنيع منتجات المخابز" },
        new ActivityType { Code = "1072", EnglishDescription = "Sugar industry", ArabicDescription = "صناعة السكر" },
        new ActivityType { Code = "1073", EnglishDescription = "Manufacture of cocoa, chocolate and sugar confectionery", ArabicDescription = "تصنيع الكاكاو والشيكولاتة والحلويات السكرية" },
        new ActivityType { Code = "1074", EnglishDescription = "Manufacturing pasta, strips, couscous and similar starchy products", ArabicDescription = "تصنيع المعكرونة وشرائطها والكسكسى والمنتجات النشوية المماثلة" },
        new ActivityType { Code = "1075", EnglishDescription = "Meals and ready-made food industry", ArabicDescription = "صناعة الوجبات و الاغذية الجاهزة" },
        new ActivityType { Code = "1079", EnglishDescription = "Manufacture of other products not classified elsewhere", ArabicDescription = "صناعة المنتجات الاخرى غير مصنفة فى موضع اخر" },
        new ActivityType { Code = "1080", EnglishDescription = "Prepared animal food industry", ArabicDescription = "صناعة الاغذية الحيوانية المجهزة" },
        new ActivityType { Code = "1101", EnglishDescription = "Spirits distilled, refined and mixed", ArabicDescription = "تقطير المشروبات الروحية وتكريرها وخلطها" },
            new ActivityType { Code = "1102", EnglishDescription = "Winemaking", ArabicDescription = "صناعة النبيذ" },
        new ActivityType { Code = "1103", EnglishDescription = "The manufacture of alcoholic drinks derived from the molten and the manufacture of molten", ArabicDescription = "صناعة المشروبات الكحولية المشتقة من المولت وصنع المولت" },
        new ActivityType { Code = "1104", EnglishDescription = "Manufacturing soft drinks and producing mineral water", ArabicDescription = "صناعة المشروبات المرطبة وانتاج المياة المعدنية" },
        new ActivityType { Code = "1200", EnglishDescription = "Manufacture of tobacco products", ArabicDescription = "صناعة منتجات التبغ" },
        new ActivityType { Code = "1311", EnglishDescription = "Processing and spinning of textile fibers", ArabicDescription = "تجهيز وغزل الياف المنسوجات" },
        new ActivityType { Code = "1312", EnglishDescription = "Textile weave", ArabicDescription = "نسج المنسوجات" },
        new ActivityType { Code = "1313", EnglishDescription = "The textile industry", ArabicDescription = "صناعة المنسوجات" },
        new ActivityType { Code = "1391", EnglishDescription = "Manufacture of knitted and crocheted fabrics", ArabicDescription = "صناعة الاقمشة التريكو والكروشية" },
        new ActivityType { Code = "1392", EnglishDescription = "Manufacture of ready-made textile accessories, except garment wear", ArabicDescription = "صناعة مستلزمات المنسوجات الجاهزة باستثناء ملابس الزينة" },
        new ActivityType { Code = "1393", EnglishDescription = "CARPet and blanket industry", ArabicDescription = "صناعة السجاد والبطاطين" },
        new ActivityType { Code = "1394", EnglishDescription = "Manufacture of ropes, thick and double ropes and nets", ArabicDescription = "صناعة الحبال والحبال الغليظة والمذدوجة والشباك" },
        new ActivityType { Code = "1399", EnglishDescription = "Other textile industry not elsewhere classified", ArabicDescription = "صناعة المنسوجات الاخرى غير مصنفة فى موضع اخر" },
        new ActivityType { Code = "1410", EnglishDescription = "Manufacture of garment with the exception of fur", ArabicDescription = "صناعة الملابس ذات الزينة باستثناء الفراء" },
        new ActivityType { Code = "1420", EnglishDescription = "Fur accessories industry", ArabicDescription = "صناعة مستلزمات الفراء" },
        new ActivityType { Code = "1430", EnglishDescription = "The manufacture of clothing, knitted and crocheted", ArabicDescription = "صناعة ملابس الزينة بالتريكو والكروشية" },
        new ActivityType { Code = "1511", EnglishDescription = "Tanning and processing of leather, fillings and dyeing of fur", ArabicDescription = "دبغ وتجهيز الجلود والحشوات وصباغة الفراء" },
        new ActivityType { Code = "1512", EnglishDescription = "Luggage, handbags and similar industries, along with saddles and horse sets", ArabicDescription = "صناعة حفائب الامتعة وحقائب اليد وما شابهة ذلك الى جانب السروج واطقم الجياد" },
        new ActivityType { Code = "1520", EnglishDescription = "Shoe manufacturing", ArabicDescription = "صناعة الاحذية" },
        new ActivityType { Code = "1610", EnglishDescription = "Sawing wood and abrasion", ArabicDescription = "نشر الخشب وسحجة" },
        new ActivityType { Code = "1621", EnglishDescription = "Sheets made of wood veneer and wood-based panels", ArabicDescription = "الصفائح من قشرة الخشب والالواح ذات الاساس الخشبى" },
        new ActivityType { Code = "1622", EnglishDescription = "Manufacture of cARPentry accessories intended for buildings and installations", ArabicDescription = "صناعة مستلزمات النجارة المعدة للابنية والمنشات" },
        new ActivityType { Code = "1623", EnglishDescription = "Wooden boxes industry", ArabicDescription = "صناعة الصناديق الخشبية" },
        new ActivityType { Code = "1629", EnglishDescription = "Manufacture of wood, wood products and cork, except furniture, and manufacture of articles produced from straw and sheets", ArabicDescription = "صناعة الاخشاب والمنتجات الخشبية والفلين باستثناء الاثاث وصناعة الاصناف المنتجة من القش والصفائح" },
        new ActivityType { Code = "1701", EnglishDescription = "Paper and carvatard pulp industry", ArabicDescription = "صناعة عجائن الورق و الورق المقوى ( الكارتون )" },
        new ActivityType { Code = "1702", EnglishDescription = "Manufacture of corrugated paper and paperboard and boxes made of paper and paperboard", ArabicDescription = "صناعة الورق والورق المقوى المموج والصناديق المصنوعة من الورق والورق المقوى" },
        new ActivityType { Code = "1709", EnglishDescription = "Manufacture of other articles of paper and paperboard", ArabicDescription = "صناعة اصناف اخرى من الورق والورق المقوى" },
        new ActivityType { Code = "1811", EnglishDescription = "printing", ArabicDescription = "الطباعة" },
        new ActivityType { Code = "1812", EnglishDescription = "Printing service activities", ArabicDescription = "انشطة الخدمات المرتبطة بالطباعة" },
        new ActivityType { Code = "1820", EnglishDescription = "Clone recorded media", ArabicDescription = "استنساخ وسائل الاعلام المسجلة" },
        new ActivityType { Code = "1910", EnglishDescription = "Coke oven products industry", ArabicDescription = "صناعة منتجات افران الكوك" },
        new ActivityType { Code = "1920", EnglishDescription = "Refined petroleum products", ArabicDescription = "المنتجات النفطية المكررة" },
        new ActivityType { Code = "2011", EnglishDescription = "Basic chemicals", ArabicDescription = "المواد الكيميائية الاساسية" },
        new ActivityType { Code = "2012", EnglishDescription = "Manufacture of fertilizers and nitrogen compounds", ArabicDescription = "صناعة الاسمدة والمركبات الازوتية" },
        new ActivityType { Code = "2013", EnglishDescription = "Plastics industry in its primary forms and synthetic rubber", ArabicDescription = "صناعة اللادائن فى اشكالها الاولية والمطاط الصناعى" },
        new ActivityType { Code = "2021", EnglishDescription = "Pesticide industry and other agricultural chemical products", ArabicDescription = "صناعة مبيدات الافات والمنتجات الكيميائية الزراعية الاخرى" },
        new ActivityType { Code = "2022", EnglishDescription = "Manufacture of paints, varnishes, and similar coatings, printing inks and molds", ArabicDescription = "صناعة الدهانات والورنيش والطلاء المماثلة واحبار الطباعة والمصطكات" },
        new ActivityType { Code = "2023", EnglishDescription = "Manufacture of soap, disinfectants, cleaning and polishing preparations, perfumes and cosmetics", ArabicDescription = "صناعة الصابون والمطهرات ومستحضرات التنظيف والتلميع والعطور ومستحضرات التجميل" },
        new ActivityType { Code = "2029", EnglishDescription = "Manufacture of other chemical products not classified elsewhere", ArabicDescription = "صناعة المنتجات الكيميائية الاخرى غير المصنفة فى موضع اخر" },
        new ActivityType { Code = "2030", EnglishDescription = "Industrial fiber industry", ArabicDescription = "صناعة الالياف الصناعية" },
        new ActivityType { Code = "2100", EnglishDescription = "Manufacture of pharmaceutical, chemical, and plant products", ArabicDescription = "صناعة المستحضرات الصيدلانية والكيميائية الدواءية والمنتجات النباتية" },
        new ActivityType { Code = "2211", EnglishDescription = "Manufacture of rubber tires and tubes, renewing and rebuilding the outer surfaces of rubber tires", ArabicDescription = "صناعة الاطارات والانابيب المطاطية وتجديد الاسطح الخارجية للاطارات المطاطية واعادة بنائها" },
        new ActivityType { Code = "2219", EnglishDescription = "Manufacture of other rubber products", ArabicDescription = "صناعة المنتجات المطاطية الاخرى" },
        new ActivityType { Code = "2220", EnglishDescription = "Plastics industry", ArabicDescription = "صناعة منتجات اللادائن" },
        new ActivityType { Code = "2310", EnglishDescription = "Glass and its products industry", ArabicDescription = "صناعة الزجاج ومنتجاتة" },
        new ActivityType { Code = "2391", EnglishDescription = "Manufacture of fusion products", ArabicDescription = "صناعة المنتجات المقاومة للانصهار" },
        new ActivityType { Code = "2392", EnglishDescription = "Manufacture of Shale products for Building", ArabicDescription = "صناعة مواد الطفلة الخاصة بالبناء" },
        new ActivityType { Code = "2393", EnglishDescription = "Manufacture of other Porcelain and ceramic products", ArabicDescription = "صناعة منتجات البرسولين والسيراميك الاخرى" },
        new ActivityType { Code = "2394", EnglishDescription = "Cement, lime and plaster industry", ArabicDescription = "صناعة الاسمنت والجير والجص" },
        new ActivityType { Code = "2395", EnglishDescription = "Manufacture of concrete products, cement and plaster", ArabicDescription = "صناعة منتجات الخرسانة والاسمنت والجص" },
        new ActivityType { Code = "2396", EnglishDescription = "Cutting, forming and completing the stone processing", ArabicDescription = "قطع وتشكيل واتمام تجهيز الاحجار" },
        new ActivityType { Code = "2399", EnglishDescription = "Manufacture of non-metallic minerals products not classified elsewhere", ArabicDescription = "صناعة منتجات المعادن الافلزية الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "2410", EnglishDescription = "The industry of basic iron and steel", ArabicDescription = "صناعة الحديد والصلب القاعديين" },
        new ActivityType { Code = "2420", EnglishDescription = "Manufacture of precious and non-ferrous basic metals", ArabicDescription = "صناعة الفلزات الثمينة وغير الحديدية القاعدية" },
        new ActivityType { Code = "2431", EnglishDescription = "Iron and steel casting", ArabicDescription = "سبك الحديدوالصلب" },
        new ActivityType { Code = "2432", EnglishDescription = "Non-ferrous metal casting", ArabicDescription = "سبك المعادن غير الحديدية" },
        new ActivityType { Code = "2511", EnglishDescription = "Structural metal products industry", ArabicDescription = "صناعة المنتجات المعدنية الانشائية" },
        new ActivityType { Code = "2512", EnglishDescription = "Industry of tanks and metal containers", ArabicDescription = "صناعة الصهاريج والخزانات و الحاويات المعدنية" },
        new ActivityType { Code = "2513", EnglishDescription = "Water vapor generators except for central heating boilers in hot water", ArabicDescription = "مولدات بخار الماء باستثناء مراجل التدفئةالمركزية بالمياة الساخنة" },
        new ActivityType { Code = "2520", EnglishDescription = "Arms and ammunition industry", ArabicDescription = "صناعة الاسلحة والذخائر" },
        new ActivityType { Code = "2591", EnglishDescription = "Forming metals by hammering, pressing, casting, rolling, and treatment of metal powders", ArabicDescription = "تشكيل المعادن بالطرق والكبس و السبك والدلفنة ومعالجة مساحيق المعادن" },
        new ActivityType { Code = "2592", EnglishDescription = "Metal processing and coating", ArabicDescription = "معالجة وطلى المعادن" },
        new ActivityType { Code = "2593", EnglishDescription = "Manufacture of cutting tools, hand tools and general metal tools", ArabicDescription = "صناعة ادوات القطع والعدد اليدوية والادوات المعدنية العامة" },
        new ActivityType { Code = "2599", EnglishDescription = "Manufacture of other fabricated metal products not classified elsewhere", ArabicDescription = "صناعة منتجات المعادن المشكلة الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "2610", EnglishDescription = "Electronic components and panels industry", ArabicDescription = "صناعة المكونات والالواح الاليكترونية" },
        new ActivityType { Code = "2620", EnglishDescription = "The manufacture of electronic computers and related devices", ArabicDescription = "صناعة الحاسبات الاليكترونية و الاجهزة المتصلة بة" },
        new ActivityType { Code = "2630", EnglishDescription = "Communications equipment industry", ArabicDescription = "صناعة اجهزة الاتصالات" },
        new ActivityType { Code = "2640", EnglishDescription = "Electronic devices industry", ArabicDescription = "صناعة الاجهزة الاليكترونية" },
        new ActivityType { Code = "2651", EnglishDescription = "Manufacturing measuring, testing, navigation and control devices", ArabicDescription = "صناعة اجهزة القياس والاختبار و الملاحة والتحكم" },
        new ActivityType { Code = "2652", EnglishDescription = "Watch and alarm clock industry", ArabicDescription = "صناعة الساعات والمنبهات" },
        new ActivityType { Code = "2660", EnglishDescription = "Radiation, medical and therapeutic electronic devices industry", ArabicDescription = "صناعة الاجهزة الاشعاعية والطبية والعلاجية اللاليكترونية" },
        new ActivityType { Code = "2670", EnglishDescription = "Optical equipment and imaging equipment industry", ArabicDescription = "صناعة المعدات البصرية واجهزة التصوير" },
        new ActivityType { Code = "2680", EnglishDescription = "Optical and magnetic conveyor industry", ArabicDescription = "صناعة الوسائل الناقلة البصرية والمغنطيسية" },
        new ActivityType { Code = "2710", EnglishDescription = "Manufacture of motors, generators, electrical transformers, devices and control panels for electricity distribution", ArabicDescription = "صناعة المحركات والمولدات والمحولات الكهربائية واجهزة ولوحات التحكم فى توزيع الكهرباء" },
        new ActivityType { Code = "2720", EnglishDescription = "Manufacture of dry and stored batteries", ArabicDescription = "صناعة البطاريات الجافة والمختزنة" },
        new ActivityType { Code = "2731", EnglishDescription = "Industrial fiber cable industry", ArabicDescription = "صناعة كابلات الالياف الصناعية" },
        new ActivityType { Code = "2732", EnglishDescription = "Other electrical and electronic wires and cables", ArabicDescription = "صناعة الاسلاك الكهربائية والاليكترونية الاخرى والكابلات" },
        new ActivityType { Code = "2733", EnglishDescription = "Wire devices industry", ArabicDescription = "صناعة اجهزة الاسلاك" },
        new ActivityType { Code = "2740", EnglishDescription = "Electrical lighting devices industry", ArabicDescription = "صناعة اجهزة الانارة الكهربائية" },
           new ActivityType { Code = "2750", EnglishDescription = "Home appliances industry", ArabicDescription = "صناعة الاجهزة المنزلية" },
        new ActivityType { Code = "2790", EnglishDescription = "Other electrical appliances industry", ArabicDescription = "صناعة الاجهزة الكهربائية الاخرى" },
        new ActivityType { Code = "2811", EnglishDescription = "Manufacture of generators and engines, with the exception of aircraft, vehicles and motorcycles", ArabicDescription = "صناعة المولدات والمحركات باستثناء الطائرات والمركبات ومحركات الموتيسيكلات" },
        new ActivityType { Code = "2812", EnglishDescription = "Liquid power devices industry", ArabicDescription = "صناعة اجهزة الطاقة السائلة" },
        new ActivityType { Code = "2813", EnglishDescription = "Manufacture of pumps, compressors, tapes and other valves", ArabicDescription = "صناعة المضخات والضواغط والاشرطة والصمامات الاخرى" },
        new ActivityType { Code = "2814", EnglishDescription = "Gears, carriers and driving devices industry", ArabicDescription = "صناعة التروس والحاملات واجهزة القيادة" },
        new ActivityType { Code = "2815", EnglishDescription = "Manufacture of furnaces, furnaces and their incinerators", ArabicDescription = "صناعة الافران و الاتونات ومحرقاتها" },
        new ActivityType { Code = "2816", EnglishDescription = "The elevators and equipment needed for it", ArabicDescription = "صناعة المصاعد والمعدات الازمة لها" },
        new ActivityType { Code = "2817", EnglishDescription = "Manufacture of office equipment and equipment (excluding electronic computers and their accessories)", ArabicDescription = "صناعة الاجهزة والمعدات المكتبية ( باستثناء الحاسبات الاليكترونية ومستلزماتها )" },
        new ActivityType { Code = "2818", EnglishDescription = "Manufacture of manual power steering equipment", ArabicDescription = "صناعة المعدات اليدوية لتوجية الطاقة" },
        new ActivityType { Code = "2819", EnglishDescription = "Other equipment industry of various purposes", ArabicDescription = "صناعة المعدات الاخرى ذات الاغراض المتنوعة" },
        new ActivityType { Code = "2821", EnglishDescription = "Agricultural and forestry equipment industry", ArabicDescription = "صناعة المعدات الزراعية والخاصة بالغابات" },
        new ActivityType { Code = "2822", EnglishDescription = "Manufacture of equipment and machinery for forming metals", ArabicDescription = "صناعة معدات واجهزة تشكيل المعادن" },
        new ActivityType { Code = "2823", EnglishDescription = "Metal equipment industry", ArabicDescription = "صناعة معدات المعادن" },
        new ActivityType { Code = "2824", EnglishDescription = "Mining and quarrying and building equipment industry", ArabicDescription = "صناعة معدات المناجم و المحاجر والبناء" },
        new ActivityType { Code = "2825", EnglishDescription = "Manufacture of food, beverage and tobacco industries equipment", ArabicDescription = "صناعة معدات الصناعات الغذائية والمشرؤبات والتبغ" },
        new ActivityType { Code = "2826", EnglishDescription = "Manufacture of ready-made clothes, accessories, and leather production", ArabicDescription = "صناعة معدات الملابس الجاهزة وهدوات الزينة وانتاج الجلود" },
        new ActivityType { Code = "2829", EnglishDescription = "Manufacture of other special-purpose equipment", ArabicDescription = "صناعة المعدات الاخرى ذات الاغراض الخاصة" },
        new ActivityType { Code = "2910", EnglishDescription = "Manufacture of motor vehicles", ArabicDescription = "صناعة المركبات ذات المحركات" },
        new ActivityType { Code = "2920", EnglishDescription = "Manufacture of motor vehicle bodies and the manufacture of trailers and semi-trailers", ArabicDescription = "صناعة هياكل المركبات ذات المحركات وصناعة المقطورات ونصف المقطورات" },
        new ActivityType { Code = "2930", EnglishDescription = "Manufacture of accessories and spare parts for motor vehicles", ArabicDescription = "صناعة مستلزمات وقطع غيار المركبات ذات المحركات" },
        new ActivityType { Code = "3011", EnglishDescription = "Building ship hulls and rafts", ArabicDescription = "بناء هياكل السفن و الطوافات" },
        new ActivityType { Code = "3012", EnglishDescription = "Manufacture of pleasure boats and sport boats", ArabicDescription = "صناعة قوارب النزهة والقوارب الرياضية" },
        new ActivityType { Code = "3020", EnglishDescription = "Railroad locomotives and rolling stock industry", ArabicDescription = "صناعة قاطرات السكك الحديدية والمعدات الدارجة على السكك الحديدية" },
        new ActivityType { Code = "3030", EnglishDescription = "Air and spacecraft industry", ArabicDescription = "صناعة المركبات الهوائية والفضائية" },
        new ActivityType { Code = "3040", EnglishDescription = "Manufacture of military military vehicles", ArabicDescription = "صناعة المركبات العسكرية الحربية" },
        new ActivityType { Code = "3091", EnglishDescription = "Industry", ArabicDescription = "صناعة" },
        new ActivityType { Code = "3092", EnglishDescription = "Manufacture of ordinary bicycles and infirm vehicles", ArabicDescription = "صناعة الدراجات العادية ومركبات العجزة" },
        new ActivityType { Code = "3099", EnglishDescription = "Other transportation equipment industry not classified elsewhere", ArabicDescription = "صناعة معدات النقل الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "3100", EnglishDescription = "Furniture Industry", ArabicDescription = "صناعة الاثاث" },
        new ActivityType { Code = "3211", EnglishDescription = "Manufacture of jewelry and related items", ArabicDescription = "صناعة المجوهرات والاصناف المتصلة بها" },
        new ActivityType { Code = "3212", EnglishDescription = "Manufacture of imitation jewelry and related items", ArabicDescription = "صناعة المجوهرات المقلدة والاصناف المتصلة بها" },
        new ActivityType { Code = "3220", EnglishDescription = "Musical instrument industry", ArabicDescription = "صناعة الالات الموسيقية" },
        new ActivityType { Code = "3230", EnglishDescription = "Sports products industry", ArabicDescription = "صناعة المنتجات الرياضية" },
        new ActivityType { Code = "3240", EnglishDescription = "Make games and play", ArabicDescription = "صناعة الالعاب واللعب" },
        new ActivityType { Code = "3250", EnglishDescription = "Manufacturing of dental and medical equipment and tools", ArabicDescription = "صناعة المعدات والادوات الطبية والخاصة بالاسنان" },
        new ActivityType { Code = "3290", EnglishDescription = "Other industries not classified elsewhere", ArabicDescription = "الصناعات الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "3311", EnglishDescription = "Repair of manufactured metal products", ArabicDescription = "اصلاح المنتجات المعدنية المصنعة" },
        new ActivityType { Code = "3312", EnglishDescription = "Machinery repair", ArabicDescription = "اصلاح الالات" },
        new ActivityType { Code = "3313", EnglishDescription = "Repair of electronic and optical devices", ArabicDescription = "اصلاح الاجهزة الاليكترونية و البصرية" },
        new ActivityType { Code = "3314", EnglishDescription = "Electronic devices repair", ArabicDescription = "اصلاح الاجهزة الاليكترونية" },
        new ActivityType { Code = "3315", EnglishDescription = "Repair of transport devices, except for motor vehicles", ArabicDescription = "اصلاح اجهزة النقل باستثناء المركبات ذات المحركات" },
        new ActivityType { Code = "3319", EnglishDescription = "Repair other devices", ArabicDescription = "اصلاح الاجهزة الاخرى" },
        new ActivityType { Code = "3320", EnglishDescription = "Installation of industrial equipment and devices", ArabicDescription = "تركيب المعدات و الاجهزة الصناعية" },
        new ActivityType { Code = "3510", EnglishDescription = "Electric generators, transformers and power distributors", ArabicDescription = "المولدات الكهربائية ومحولات وموزعات الكهرباء" },
        new ActivityType { Code = "3520", EnglishDescription = "Manufacture of sulfur gas and distribution of gaseous fuels by means of main pipes", ArabicDescription = "صناعة غاز الاستصباح وتوزيع انواع الوقود الغازية عن طريق مواسير رئيسية" },
        new ActivityType { Code = "3530", EnglishDescription = "Steam supply and air conditioning", ArabicDescription = "توريد البخار واجهزة تكييف الهواء" },
        new ActivityType { Code = "3600", EnglishDescription = "Water collection, treatment and supply", ArabicDescription = "تجميع ومعالجة وتوريد المياة" },
        new ActivityType { Code = "3700", EnglishDescription = "Sewer", ArabicDescription = "المجارى" },
        new ActivityType { Code = "3811", EnglishDescription = "Collection of non-hazardous waste", ArabicDescription = "تجميع المخلفات غير الخطرة" },
        new ActivityType { Code = "3812", EnglishDescription = "Collection of hazardous waste", ArabicDescription = "تجميع المخلفات الخطرة" },
        new ActivityType { Code = "3821", EnglishDescription = "Treatment and disposal of non-hazardous waste", ArabicDescription = "معالجة والتصرف فى المخلفات غير الخطرة" },
        new ActivityType { Code = "3822", EnglishDescription = "Treatment and disposal of hazardous waste", ArabicDescription = "معالجة والتصرف فى المخلفات الخطرة" },
        new ActivityType { Code = "3830", EnglishDescription = "Material handling", ArabicDescription = "معالجة المواد" },
        new ActivityType { Code = "3900", EnglishDescription = "Recycling activities and services and the disposal of other waste", ArabicDescription = "انشطة وخدمات اعادة التدوير والتصرف فى النفايات الاخرى" },
        new ActivityType { Code = "4100", EnglishDescription = "Building constructions", ArabicDescription = "انشاءات المبانى" },
        new ActivityType { Code = "4210", EnglishDescription = "Road and railway constructions", ArabicDescription = "الانشاءات الخاصة بالطرق والسكك الحديدية" },
        new ActivityType { Code = "4220", EnglishDescription = "Construction for projects of public benefit", ArabicDescription = "الانشاءات الخاصة بالمشاريع ذات المنفعة العامة" },
        new ActivityType { Code = "4290", EnglishDescription = "Construction for other civil engineering projects", ArabicDescription = "الانشاءات الخاصة بالمشاريع الهندسية المدنية الاخرى" },
        new ActivityType { Code = "4311", EnglishDescription = "Remove the installations", ArabicDescription = "ازالة المنشات" },
        new ActivityType { Code = "4312", EnglishDescription = "Preparing sites", ArabicDescription = "اعداد المواقع" },
        new ActivityType { Code = "4321", EnglishDescription = "Electrical installations", ArabicDescription = "التركيبات الكهربائية" },
        new ActivityType { Code = "4322", EnglishDescription = "Plumbing, heating and air-conditioning installations", ArabicDescription = "التركيبات الخاصة بالسباكة والتدفئة ومكيفات الهواء" },
        new ActivityType { Code = "4329", EnglishDescription = "Other structural installations", ArabicDescription = "التركيبات الانشائية الاخرى" },
        new ActivityType { Code = "4330", EnglishDescription = "Completion and finishing of buildings", ArabicDescription = "استكمال وتشطيب المبانى" },
        new ActivityType { Code = "4390", EnglishDescription = "Other specialized construction activities", ArabicDescription = "انشطة الانشاءات المتخصصة الاخرى" },
        new ActivityType { Code = "4510", EnglishDescription = "Sale of motor vehicles", ArabicDescription = "بيع المركبات ذات المحركات" },
        new ActivityType { Code = "4520", EnglishDescription = "Maintenance and repair of motor vehicles", ArabicDescription = "صيانة واصلاح المركبات ذات المحركات" },
        new ActivityType { Code = "4530", EnglishDescription = "Sale of motor vehicle parts and accessories", ArabicDescription = "بيع قطع غيار ومستلزمات المركبات ذات المحركات" },
        new ActivityType { Code = "4540", EnglishDescription = "Sale, maintenance and repair of motorcycles, parts and accessories thereof", ArabicDescription = "بيع وصيانة واصلاح الدراجات النارية وقطع الغيار والمستلزمات الخاصة بها" },
        new ActivityType { Code = "4610", EnglishDescription = "Wholesale trade on the basis of a contract or a fee", ArabicDescription = "تجارة الجملة على اساس عقد او نظير رسم" },
        new ActivityType { Code = "4620", EnglishDescription = "Wholesale trade in agricultural raw materials and live animals", ArabicDescription = "تجارة الجملة الخاصة بالمواد الاولية الزراعية والحيوانات الحية" },
        new ActivityType { Code = "4630", EnglishDescription = "Wholesale trade of food, beverages and tobacco", ArabicDescription = "تجارة الجملة الخاصة بالاغذية والمشرؤبات والتبغ" },
        new ActivityType { Code = "4641", EnglishDescription = "Wholesale trade of clothes, fabrics and shoes", ArabicDescription = "تجارة الجملة الخاصة بالملابس والاقمشة والاحذية" },
        new ActivityType { Code = "4649", EnglishDescription = "Wholesale trade for other household appliances", ArabicDescription = "تجارة الجملة الخاصة بالادوات المنزلية الاخرة" },
        new ActivityType { Code = "4651", EnglishDescription = "Wholesale trade of computer hardware, accessories and computer software", ArabicDescription = "تجارة الجملة الخاصة باجهزة الكمبيوتر ومستلزماتها وبرامج الكمبيوتر" },
        new ActivityType { Code = "4652", EnglishDescription = "Wholesale trade of electronic devices, communications devices and accessories", ArabicDescription = "تجارة الجملة الخاصة بالاجهزة الاليكترونية واجهزة الاتصالات ومستلزماتها" },
        new ActivityType { Code = "4653", EnglishDescription = "Wholesale trade for agricultural equipment, machinery and supplies", ArabicDescription = "تجارة الجملة الخاصة بالمعدات والالات والتوريدات الزراعية" },
        new ActivityType { Code = "4659", EnglishDescription = "Wholesale trade of equipment and other devices", ArabicDescription = "تجارة الجملة الخاصة بالمعدات والاجهزة الاخرى" },
        new ActivityType { Code = "4661", EnglishDescription = "Wholesale trade of dry, liquid and gaseous fuels and related products", ArabicDescription = "تجارة الجملة الخاصة بالوقود الجاف والسائل والغازى والمنتجات المرتبطة بذلك" },
        new ActivityType { Code = "4662", EnglishDescription = "Wholesale trade in precious metals and minerals", ArabicDescription = "تجارة الجملة الخاصة بالمعادن والمعادن النفيسة" },
        new ActivityType { Code = "4663", EnglishDescription = "Wholesale trade, supplies and equipment for building materials, hardware, plumbing and heating appliances", ArabicDescription = "تجارة الجملة والتوريدات والاجهزة الخاصة بمواد البناء والادوات المعدنية والسباكة واجهزة التدفئة" },
        new ActivityType { Code = "4669", EnglishDescription = "Wholesale trade for waste, waste and other products not classified elsewhere", ArabicDescription = "تجارة الجملة الخاصة بالنفايات والمخلفات والمنتجات الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "4690", EnglishDescription = "Non-specialized wholesale trade", ArabicDescription = "تجارة الجملة غير المتخصصة" },
         new ActivityType { Code = "4711", EnglishDescription = "Retail sale in non-specialized stores of food, beverages or tobacco", ArabicDescription = "البيع بالتجزئة بالمتاجر غير المتخصصة للاغذية والمشروبات اوالتبغ" },
        new ActivityType { Code = "4719", EnglishDescription = "Other retail types in non-specialized stores", ArabicDescription = "انواع البيع بالتجزئةالاخرى بالمتاجر غير المتخصصة" },
        new ActivityType { Code = "4721", EnglishDescription = "Retail sale in specialized food stores", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للاغذية" },
        new ActivityType { Code = "4722", EnglishDescription = "Retail sale in specialized stores for drinks", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للمشروبات" },
        new ActivityType { Code = "4723", EnglishDescription = "Retail sale in specialized stores of tobacco products", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة لمنتجات التبغ" },
        new ActivityType { Code = "4730", EnglishDescription = "Retail sale of specialized vehicles for fuel", ArabicDescription = "البيع بالتجزئة بالاماكن المتخصصة لوقود المركبات" },
        new ActivityType { Code = "4741", EnglishDescription = "Retail sale in stores specialized in computer hardware, accessories, computer software, and communications equipment", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة فى اجهزة الحاسب الالى ومستلزماتة وبرامج الكمبيوتر واجهزة الاتصالات" },
        new ActivityType { Code = "4751", EnglishDescription = "Retail sale in clothing stores", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة فى الملابس" },
        new ActivityType { Code = "4752", EnglishDescription = "Retail sale in specialized stores of hardware, paint and glass", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للادوات المعدنية و الطلاء والزجاج" },
        new ActivityType { Code = "4753", EnglishDescription = "Retail sale in specialized stores of cARPets, blankets, wall and floor coverings", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للسجاد والبطاطين واغطية الحوائط والارضيات" },
        new ActivityType { Code = "4759", EnglishDescription = "Retail sale in specialized stores of household electrical appliances, furniture, lighting equipment and other household appliances", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للاجهزة الكهربائية المنزلية والاثاث واجخزة الانارة والادوات المنزلية الاخرى" },
        new ActivityType { Code = "4761", EnglishDescription = "Retail sale in specialized stores of books, newspapers, and stationery", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للكتب والصحف والادوات المكتبية" },
        new ActivityType { Code = "4762", EnglishDescription = "Retail sale in specialized stores of music and video recordings", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للتسجيلات الموسشيقية والمرئية" },
        new ActivityType { Code = "4763", EnglishDescription = "Retail sale in specialized stores of sports equipment", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للادوات الرياضية" },
        new ActivityType { Code = "4764", EnglishDescription = "Retail sale in specialized games and toys stores", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للالعاب واللعب" },
        new ActivityType { Code = "4771", EnglishDescription = "Retail sale in specialized stores of shoes, clothing and leather products", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للاحذية والملابس والمنتجات الجلدية" },
        new ActivityType { Code = "4772", EnglishDescription = "Retail sale in specialized stores of pharmaceutical, medical and pharmaceutical products, ornamental and cosmetic products", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للمنتجات والعقاقير الصيدلانية والطبية وادوات الزينة والمنتجات التجميلية" },
        new ActivityType { Code = "4773", EnglishDescription = "Retail sale in specialized stores of other new products", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة للمنتجات الجديدة الاخرى" },
        new ActivityType { Code = "4774", EnglishDescription = "Retail sale of used products", ArabicDescription = "البيع بالتجزئة للمنتجات المستعملة" },
        new ActivityType { Code = "4781", EnglishDescription = "Retail sale through kiosks and markets of food, soft drinks and tobacco products", ArabicDescription = "البيع بالتجزئة من خلال الاكشاك والاسواق للمواد الغذائية والمشروبات الخفيفة ومنتجات التبغ" },
        new ActivityType { Code = "4782", EnglishDescription = "Retail sale through kiosks and markets of clothes, fabrics and shoes", ArabicDescription = "البيع بالتجزئة من خلال الاكشاك والاسواق للملابس والاقمشة والاحذية" },
        new ActivityType { Code = "4789", EnglishDescription = "Retail sale via stalls of other products", ArabicDescription = "البيع بالتجزئة من خلال الاكشاك للمنتجات الاخرى" },
        new ActivityType { Code = "4742", EnglishDescription = "Retail sale in stores specialized in audio-visual equipment", ArabicDescription = "البيع بالتجزئة بالمتاجر المتخصصة فى الاجهزة السمعية والبصرية" },
        new ActivityType { Code = "4791", EnglishDescription = "Retail sale via mail requests or through the Internet", ArabicDescription = "البيع بالتجزئة عبر طلبات البريد او من خلال الانترنت" },
        new ActivityType { Code = "4799", EnglishDescription = "Other types of retail sales that do not take place in stores, kiosks or markets", ArabicDescription = "انواع البيع بالتجزئةالاخرى التى لاتتم بالنتاجر او الاكشاك او الاسواق" },
        new ActivityType { Code = "4911", EnglishDescription = "Inland passenger transportation", ArabicDescription = "النقل الداخلى للركاب" },
        new ActivityType { Code = "4912", EnglishDescription = "Shipping by rail", ArabicDescription = "الشحن عن طريق السكك الحديدية" },
        new ActivityType { Code = "4921", EnglishDescription = "Transporting land passengers outside and inside cities", ArabicDescription = "نقل الركاب البرى خارج وداخل المدن" },
        new ActivityType { Code = "4922", EnglishDescription = "Other types of passenger transport by land", ArabicDescription = "انواع نقل الركاب البرية الاخرى" },
        new ActivityType { Code = "4923", EnglishDescription = "Land transportation of goods by bus", ArabicDescription = "النقل البرى للبضائع عن طريق الحافلات" },
        new ActivityType { Code = "4930", EnglishDescription = "Pipeline transportation", ArabicDescription = "النقل عبر خطوط الانابيب" },
        new ActivityType { Code = "5011", EnglishDescription = "Transportation of marine and coastal passengers", ArabicDescription = "نقل الركاب البحرى والساحلى" },
        new ActivityType { Code = "5012", EnglishDescription = "Marine and coastal cargo transportation", ArabicDescription = "نقل البضائع البحرى والساحلى" },
        new ActivityType { Code = "5021", EnglishDescription = "Inland passenger water transport", ArabicDescription = "النقل الداخلى المائى للركاب" },
        new ActivityType { Code = "5022", EnglishDescription = "Inland water transport of goods", ArabicDescription = "النقل الداخلى المائى للبضائع" },
        new ActivityType { Code = "5110", EnglishDescription = "Air transport of passengers", ArabicDescription = "النقل الجوى للركاب" },
        new ActivityType { Code = "5120", EnglishDescription = "Air freight transport", ArabicDescription = "النقل الجوى للبضائع" },
        new ActivityType { Code = "5210", EnglishDescription = "Keep and store", ArabicDescription = "الاحتفاظ والتخزين" },
        new ActivityType { Code = "5221", EnglishDescription = "Service activities related to road transport", ArabicDescription = "انشطة الخدمات المتصلة بالنقل البرى" },
        new ActivityType { Code = "5222", EnglishDescription = "Emergency service activities related to maritime transport", ArabicDescription = "انشطة الخدمات الطارئة المتصلة بالنقل البحرى" },
        new ActivityType { Code = "5223", EnglishDescription = "Emergency service activities related to air transport", ArabicDescription = "انشطة الخدمات الطارئة المتصلة بالنقل الجوى" },
        new ActivityType { Code = "5224", EnglishDescription = "Cargo handling", ArabicDescription = "مناولة البضائع" },
        new ActivityType { Code = "5229", EnglishDescription = "Other activities in support of the transfer", ArabicDescription = "الانشطة الاخرى الداعمة للنقل" },
        new ActivityType { Code = "5310", EnglishDescription = "Mail activities", ArabicDescription = "انشطة البريد" },
        new ActivityType { Code = "5320", EnglishDescription = "Parcel delivery activities", ArabicDescription = "انشطة تسليم الطرود" },
        new ActivityType { Code = "5510", EnglishDescription = "Short-term placement activities (rental - housing", ArabicDescription = "انشطة التسكين قصيرة المدة" },
        new ActivityType { Code = "5520", EnglishDescription = "Campgrounds, parking lots, and locomotives", ArabicDescription = "اراضى المخيمات ومواقف مركبات التنزهة والقاطرات" },
        new ActivityType { Code = "5590", EnglishDescription = "Other types of placement", ArabicDescription = "انواع التسكين الاخرى" },
        new ActivityType { Code = "5610", EnglishDescription = "Restaurant service and food delivery activities by mobile means", ArabicDescription = "انشطة خدمات المطاعم وتوصيل الطعام بالوسائل المتحركة" },
        new ActivityType { Code = "5621", EnglishDescription = "Event catering", ArabicDescription = "تقديم الطعام بالمناسبات" },
        new ActivityType { Code = "5629", EnglishDescription = "Other catering services activities", ArabicDescription = "انشطة خدمات تقديم الطعام الاخرى" },
        new ActivityType { Code = "5630", EnglishDescription = "Light beverage service activities", ArabicDescription = "انشطة خدمات تقديم المشروبات الخفيفة" },
        new ActivityType { Code = "5811", EnglishDescription = "Publishing books", ArabicDescription = "نشر الكتب" },
        new ActivityType { Code = "5812", EnglishDescription = "Publish the directory and address lists", ArabicDescription = "نشر الدليل وقوائم العناوين" },
        new ActivityType { Code = "5813", EnglishDescription = "Publishing newspapers, magazines and periodicals", ArabicDescription = "نشر الصحف والمجلات والدوريات" },
        new ActivityType { Code = "5819", EnglishDescription = "Other publishing activities", ArabicDescription = "انشطة النشر الاخرى" },
        new ActivityType { Code = "5820", EnglishDescription = "Computer Software Publishing", ArabicDescription = "نشر برامج الحاسب الالى" },
        new ActivityType { Code = "5911", EnglishDescription = "Film, video and television program production activities", ArabicDescription = "انشطة انتاج الافلام السينمائية والفيديو وبرامج التليفزيون" },
        new ActivityType { Code = "5912", EnglishDescription = "Subsequent activities for the production of movies, videos and television programs", ArabicDescription = "الانشطة الاحقة لانتاج الافلام السينمائية والفيديو وبرامج التليفزيون" },
        new ActivityType { Code = "5913", EnglishDescription = "Motion picture, video and television program distribution activities", ArabicDescription = "انشطة توزيع الافلام السينمائية والفيديو وبرامج التليفزيون" },
        new ActivityType { Code = "5914", EnglishDescription = "Film screening activities", ArabicDescription = "انشطة عرض الافلام السينمائية" },
        new ActivityType { Code = "5920", EnglishDescription = "Production and publishing of sound and music recordings", ArabicDescription = "انشطة انتاج ونشر التسجيلات الصوتية والموسيقية" },
        new ActivityType { Code = "6010", EnglishDescription = "Broadcasting over radio stations", ArabicDescription = "البث عبر محطات الراديو" },
        new ActivityType { Code = "6020", EnglishDescription = "Television program preparation and broadcast activities", ArabicDescription = "انشطة اعداد برامج التليفزيون وبثها" },
        new ActivityType { Code = "6110", EnglishDescription = "Wired telecommunications activities", ArabicDescription = "انشطة الاتصالات السلكية" },
        new ActivityType { Code = "6120", EnglishDescription = "Wireless communication activities", ArabicDescription = "انشطة الاتصالات اللاسلكية" },
        new ActivityType { Code = "6130", EnglishDescription = "Satellite communication activities", ArabicDescription = "انشطة الاتصالات عبر الاقمار الصناعية" },
        new ActivityType { Code = "6190", EnglishDescription = "Other telecommunications activities", ArabicDescription = "انشطة الاتصالات السلكية و اللاسلكية الاخرى" },
        new ActivityType { Code = "6201", EnglishDescription = "Computer program preparation activities", ArabicDescription = "انشطة اعداد برامج الحاسب الالى" },
        new ActivityType { Code = "6202", EnglishDescription = "Computer consultancy experience and facilities management activities related to computer fields", ArabicDescription = "الخبرة الاستشارية فى مجال الحاسب الالى وانشطة ادارة التسهيلات المتصلة بمجالات الحاسب الالى" },
        new ActivityType { Code = "6209", EnglishDescription = "Other activities related to information technology and computer services", ArabicDescription = "الانشطة الاخرى المتصلة بتكنولوجيا المعلومات وخدمات الحاسب الالى" },
        new ActivityType { Code = "6311", EnglishDescription = "Data processing, hosting and related activities", ArabicDescription = "معالجة البيانات والاستضافة والانشطة المتصلة بذلك" },
        new ActivityType { Code = "6312", EnglishDescription = "Electronic portals", ArabicDescription = "البوابات الاليكترونية" },
        new ActivityType { Code = "6391", EnglishDescription = "Activities of press agencies", ArabicDescription = "انشطة الوكالات الصحفية" },
        new ActivityType { Code = "6399", EnglishDescription = "Other activities for information services that are not classified in other locations", ArabicDescription = "الانشطة الاخرى لخدمات تقديم المعلومات غير المصنفة فى مواقع اخرى" },
        new ActivityType { Code = "6411", EnglishDescription = "Central banks", ArabicDescription = "المصارف المركزية" },
        new ActivityType { Code = "6419", EnglishDescription = "Other financial intermediaries", ArabicDescription = "الوساطات المالية الاخرى" },
        new ActivityType { Code = "6420", EnglishDescription = "Activities of holding companies", ArabicDescription = "انشطة الشركات القابضة" },
        new ActivityType { Code = "6430", EnglishDescription = "Credit activities, provision of credits, and similar financial entities", ArabicDescription = "انشطةالائتمان وتوفير الاعتمادات والكيانات المالية المشابهة" },
        new ActivityType { Code = "6491", EnglishDescription = "Financial leasing", ArabicDescription = "التاجير المالى" },
        new ActivityType { Code = "6492", EnglishDescription = "Other forms of loans granted", ArabicDescription = "اشكال القروض الممنوحة الاخرى" },
        new ActivityType { Code = "6499", EnglishDescription = "Other financial services activities, with the exception of insurance and credit provision activities for pensions not classified in other locations", ArabicDescription = "انشطة الخدمات المالية الاخرى , باستثناء التامين وانشطة توفير الاعتمادات للمعاشات التقاعدية غير المصنفة فى مواقع اخرى" },
        new ActivityType { Code = "6511", EnglishDescription = "Life insurance", ArabicDescription = "التامين على الحياة" },
        new ActivityType { Code = "6512", EnglishDescription = "Non-life insurance", ArabicDescription = "التامين على غير الحياة" },
        new ActivityType { Code = "6520", EnglishDescription = "Reinsurance", ArabicDescription = "اعادة التامين" },
        new ActivityType { Code = "6530", EnglishDescription = "Providing credits for pensions", ArabicDescription = "توفير الاعتمادات للمعاشات التقاعدية" },
        new ActivityType { Code = "6611", EnglishDescription = "Financial markets management", ArabicDescription = "ادارة الاسواق المالية" },
        new ActivityType { Code = "6612", EnglishDescription = "Security and commodity contracts brokerage", ArabicDescription = "الامن وسمسرة عقود السلع" },
        new ActivityType { Code = "6619", EnglishDescription = "Auxiliary activities for financial services", ArabicDescription = "الانشطة المساعدة للخدمات المالية" },
        new ActivityType { Code = "6621", EnglishDescription = "Risk and damage assessment", ArabicDescription = "تقدير المخاطر والتلفيات" },
        new ActivityType { Code = "6622", EnglishDescription = "Activities of insurance and brokerage agents", ArabicDescription = "انشطة وكلاء التامين والسمسرة" },
        new ActivityType { Code = "6629", EnglishDescription = "Other activities auxiliary to insurance and provision for pensions", ArabicDescription = "الانشطة الاخرى المساعدة للتامين وتوفير الاعتمادات للمعاشات التقاعدية" },
        new ActivityType { Code = "6630", EnglishDescription = "Financial credit management activities", ArabicDescription = "انشطة ادارة الاعتمادات المالية" },
        new ActivityType { Code = "6810", EnglishDescription = "Real estate activities with own or leased property", ArabicDescription = "الانشطة العقارية فى الممتلكات المملوكة او المؤجرة" },
        new ActivityType { Code = "6820", EnglishDescription = "Real estate activities on the basis of a contract or a fee", ArabicDescription = "الانشطة العقارية على اساس عقد او نظير رسم" },
        new ActivityType { Code = "6910", EnglishDescription = "Legal activities", ArabicDescription = "الانشطة القانونية" },
        new ActivityType { Code = "6920", EnglishDescription = "Accounting, auditing, bookkeeping and tax advice activities", ArabicDescription = "الانشطة المحاسبية والمراجعة ومسك الدفاتر والاستشارات الضرائبية" },
        new ActivityType { Code = "7010", EnglishDescription = "Main office activities", ArabicDescription = "انشطة المكاتب الرئيسية" },
        new ActivityType { Code = "7020", EnglishDescription = "Management consultancy activities", ArabicDescription = "الانشطة الاستشارية الخاصة بالادارة" },
        new ActivityType { Code = "7110", EnglishDescription = "Architectural and engineering activities and related technical consulting", ArabicDescription = "الانشطة المعمارية والهندسية و الاستشارات الفنية المتصلة بذلك" },
        new ActivityType { Code = "7120", EnglishDescription = "Technical tests and analyzes", ArabicDescription = "الاختبارات والتحليلات الفنية" },
        new ActivityType { Code = "7210", EnglishDescription = "Research and experimental development in the field of natural and engineering sciences", ArabicDescription = "البحث والتطوير التجريبى فى مجال العلوم الطبيعية والهندسية" },
        new ActivityType { Code = "7220", EnglishDescription = "Experimental research and development in the field of social and human sciences", ArabicDescription = "البحث والتطوير التجريبى فى مجال العلوم الاجتماعية والانسانية" },
        new ActivityType { Code = "7310", EnglishDescription = "Advertising", ArabicDescription = "الاعلان" },
        new ActivityType { Code = "7320", EnglishDescription = "Market studies and public opinion polls", ArabicDescription = "دراسات السوق واستطلاعات الراى العام" },
        new ActivityType { Code = "7410", EnglishDescription = "Specialized design activities", ArabicDescription = "انشطة التصميمات المتخصصة" },
        new ActivityType { Code = "7420", EnglishDescription = "Photographic activities", ArabicDescription = "الانشطة الفوتوغرافية" },
        new ActivityType { Code = "7490", EnglishDescription = "Other specialized, scientific and artistic activities not classified elsewhere", ArabicDescription = "الانشطة الاخرى التخصصية والعلمية والفنية غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "7500", EnglishDescription = "Veterinary activities", ArabicDescription = "الانشطة البيطرية" },
        new ActivityType { Code = "7710", EnglishDescription = "Renting motor vehicles", ArabicDescription = "تاجيرواستئجار المركبات ذات المحركات" },
        new ActivityType { Code = "7721", EnglishDescription = "Renting and renting sports and leisure products and tools", ArabicDescription = "تاجير واستئجار منتجات والادوات الرياضية والترفيهية" },
        new ActivityType { Code = "7722", EnglishDescription = "Rental of video tapes and CDs", ArabicDescription = "تاجير شرائط واسطوانات الفيديو" },
        new ActivityType { Code = "7729", EnglishDescription = "Renting and renting other personal and household products", ArabicDescription = "تاجيرواستئجار المنتجات الشخصية والمنزلية الاخرى" },
        new ActivityType { Code = "7730", EnglishDescription = "Renting and leasing of other physical devices and equipment", ArabicDescription = "تاجير واستئجار الاجهزة والمعدات المادية الاخرى" },
        new ActivityType { Code = "7740", EnglishDescription = "Rent forms of intellectual property and similar products, except for copyright works", ArabicDescription = "استئجار اشكال الملكية الفكرية والمنتجات المشابهة باستثناء اعمال حقوق المؤلف" },
        new ActivityType { Code = "7810", EnglishDescription = "Activities of recruitment and appointment agencies", ArabicDescription = "انشطة وكالات التوظيف والتعيين" },
        new ActivityType { Code = "7820", EnglishDescription = "Activities of temporary employment agencies", ArabicDescription = "انشطة وكالات التوظيف المؤقت" },
        new ActivityType { Code = "7830", EnglishDescription = "Providing other human resources", ArabicDescription = "توفير المصادر البشرية الاخرى" },
        new ActivityType { Code = "7911", EnglishDescription = "Tourism agency services", ArabicDescription = "خدمات وكالات السياحة" },
        new ActivityType { Code = "7912", EnglishDescription = "Activities of tour guides", ArabicDescription = "انشطة المرشدين السياحيين" },
        new ActivityType { Code = "7990", EnglishDescription = "Other types of reservations and related activities", ArabicDescription = "انواع الحجوزات الاخرى والانشط المتصلة بذلك" },
        new ActivityType { Code = "8010", EnglishDescription = "Private security activities", ArabicDescription = "انشطة الامن الخاص" },
        new ActivityType { Code = "8020", EnglishDescription = "Security systems services activities", ArabicDescription = "انشطة خدمات انظمة الامن" },
        new ActivityType { Code = "8030", EnglishDescription = "Investigation activities", ArabicDescription = "انشطة التحرى" },
        new ActivityType { Code = "8110", EnglishDescription = "Support activities for joint facilities", ArabicDescription = "انشطة دعم التسهيلات المشتركة" },
        new ActivityType { Code = "8121", EnglishDescription = "General cleaning of buildings", ArabicDescription = "النظافة العامة للمبانى" },
        new ActivityType { Code = "8129", EnglishDescription = "Building cleaning activities and other industrial facilities", ArabicDescription = "انشطة تنظيف المبانى والمنشات الصناعية الاخرى" },
        new ActivityType { Code = "8130", EnglishDescription = "Gardening services and maintenance activities", ArabicDescription = "انشطة خدمات رعاية وصيانة الحدائق" },
        new ActivityType { Code = "8211", EnglishDescription = "Joint office support services activities", ArabicDescription = "انشطة خدمات الدعم المكتبية المشتركة" },
        new ActivityType { Code = "8219", EnglishDescription = "Photocopying, document processing and other specialized office support services activities", ArabicDescription = "النسخ وتجهيز المستندات وانشطة خدمات الدعم المكتبية المتخصصة الاخرى" },
        new ActivityType { Code = "8220", EnglishDescription = "Information center services", ArabicDescription = "خدمات مراكز الاستعلامات" },
        new ActivityType { Code = "8230", EnglishDescription = "Organizing trade conferences and exhibitions", ArabicDescription = "تنظيم المؤتمرات والمعارض التجارية" },
        new ActivityType { Code = "8291", EnglishDescription = "Activities of collection agencies and lending offices", ArabicDescription = "انشطة وكالات التحصيل ومكاتب الاقراض" },
        new ActivityType { Code = "8292", EnglishDescription = "Packaging activities", ArabicDescription = "انشطة التغليف" },
        new ActivityType { Code = "8299", EnglishDescription = "Other support services activities that are not classified in other locations", ArabicDescription = "انشطة خدمات الدعم الاخرى الخاصة بالاعمال التجارية غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "8411", EnglishDescription = "Public administration activities", ArabicDescription = "انشطة الادارات العامة" },
        new ActivityType { Code = "8412", EnglishDescription = "Organizing activities to provide health care, education, educational services and other social services, with the exception of social security", ArabicDescription = "تنظيم انشطة تقديم العناية الصحية والتعليم والخدمات التثقيفية والخدمات الاجتماعية الاخرى باستثناء الضمان الاجتماعى" },
        new ActivityType { Code = "8413", EnglishDescription = "Organize and contribute to effective business operations", ArabicDescription = "تنظيم والمساهمة فى عمليات الاعمال التجارية الفعالة" },
        new ActivityType { Code = "8421", EnglishDescription = "Foreign affairs", ArabicDescription = "الشئون الخارجية" },
        new ActivityType { Code = "8422", EnglishDescription = "Defense activities", ArabicDescription = "انشطة الدفاع" },
        new ActivityType { Code = "8423", EnglishDescription = "Security and public order activities", ArabicDescription = "انشطة الامن والنظام العام" },
        new ActivityType { Code = "8430", EnglishDescription = "Compulsory social insurance activities", ArabicDescription = "انشطة التامين الاجتماعى الاجبارى" },
        new ActivityType { Code = "8510", EnglishDescription = "Primary and pre-primary education", ArabicDescription = "التعليم الابتدائى وقبل الابتدائى" },
        new ActivityType { Code = "8521", EnglishDescription = "General secondary education", ArabicDescription = "التعليم الثانوى العام" },
        new ActivityType { Code = "8522", EnglishDescription = "Technical and vocational secondary education", ArabicDescription = "التعليم الثانوى الفنى والهنى" },
        new ActivityType { Code = "8530", EnglishDescription = "Higher Education", ArabicDescription = "التعليم العالى" },
        new ActivityType { Code = "8541", EnglishDescription = "Sports and rehabilitation education", ArabicDescription = "التعليم الرياضى والتاهيلى" },
        new ActivityType { Code = "8542", EnglishDescription = "Cultural education", ArabicDescription = "التعليم الثقافى" },
        new ActivityType { Code = "8549", EnglishDescription = "Other types of education not classified elsewhere", ArabicDescription = "انواع التعليم الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "8550", EnglishDescription = "Activities in support of education", ArabicDescription = "الانشطة الداعمة للتعليم" },
        new ActivityType { Code = "8610", EnglishDescription = "Hospital activities", ArabicDescription = "انشطة المستشفيات" },
        new ActivityType { Code = "8620", EnglishDescription = "Activities related to medicine and dentistry", ArabicDescription = "الانشطة المتصلة بالطب وطب الاسنان" },
        new ActivityType { Code = "8690", EnglishDescription = "Other activities related to human health", ArabicDescription = "الانشطة الاخرى المتصلة بصحة الانسان" },
        new ActivityType { Code = "8710", EnglishDescription = "Nursing facilities for sanatoriums", ArabicDescription = "تسهيلات العناية بالتمريض بالمصحات" },
        new ActivityType { Code = "8720", EnglishDescription = "Nursing care facilities for special needs clinics, mental illnesses and physical abuse", ArabicDescription = "تسهيلات العناية بالتمريض بالمصحات الخاصة بذوى الاحتياجات الخاصة والامراض العقلية والانتهاكات البدنية" },
        new ActivityType { Code = "8730", EnglishDescription = "Spa facilities for the elderly and disabled", ArabicDescription = "تسهيلات العناية بالمصحات الخاصة بالعجائز والمقعدين" },
        new ActivityType { Code = "8790", EnglishDescription = "Other spa care facilities", ArabicDescription = "تسهيلات العناية الاخرى بالمصحات" },
        new ActivityType { Code = "8810", EnglishDescription = "Social work activities for the infirm and disabled that take place without accommodation", ArabicDescription = "انشطة الاعمال الاجتماعية للعجزة والمقعدين التى تتم بدون اقامة" },
        new ActivityType { Code = "8890", EnglishDescription = "Other social business activities that take place without residence", ArabicDescription = "انشطة الاعمال الاجتماعية الاخرى التى تتم بدون اقامة" },
        new ActivityType { Code = "9000", EnglishDescription = "Creative and recreational art activities", ArabicDescription = "انشطة الفن الابداعى والترفية" },
        new ActivityType { Code = "9101", EnglishDescription = "Library and archive activities", ArabicDescription = "انشطة المكتبات والارشيف" },
        new ActivityType { Code = "9102", EnglishDescription = "Museum activities and restoration of historic sites and buildings", ArabicDescription = "انشطة المتاحف وعمليات ترميم المواقع والمبانى التاريخية" },
        new ActivityType { Code = "9103", EnglishDescription = "Botanical and zoological gardens and natural wildlife activities", ArabicDescription = "حدائق النباتات والحيوانات وانشطة الحياة البرية الطبيعية" },
        new ActivityType { Code = "9200", EnglishDescription = "Betting activities and gambling", ArabicDescription = "انشطة المراهنات والعاب القمار" },
        new ActivityType { Code = "9311", EnglishDescription = "Providing sports facilities", ArabicDescription = "توفير التسهيلات الرياضية" },
        new ActivityType { Code = "9312", EnglishDescription = "Sports club activities", ArabicDescription = "انشطة النوادى الرياضية" },
        new ActivityType { Code = "9319", EnglishDescription = "Other sports activities", ArabicDescription = "الانشطة الرياضية الاخرى" },
        new ActivityType { Code = "9321", EnglishDescription = "Recreational activities and performances in parks", ArabicDescription = "الانشطة الترفيهية والعروض التى تتم بالمتنزهات" },
        new ActivityType { Code = "9329", EnglishDescription = "Other leisure and entertainment activities not classified elsewhere", ArabicDescription = "الانشطة الترفيهية والمسلية الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "9411", EnglishDescription = "The activities of commercial enterprises, employers and professional membership organizations", ArabicDescription = "انشطة المؤسسات التجارية وارباب العمل ومنظمات العضوية المهنية" },
        new ActivityType { Code = "9412", EnglishDescription = "Activities of professional membership organizations", ArabicDescription = "انشطة منظمات العضوية المهنية" },
        new ActivityType { Code = "9420", EnglishDescription = "Trade union activities", ArabicDescription = "انشطة النقابات التجارية" },
        new ActivityType { Code = "9491", EnglishDescription = "Activities of religious organizations", ArabicDescription = "انشطة المنظمات الدينية" },
        new ActivityType { Code = "9492", EnglishDescription = "Activities of political organizations", ArabicDescription = "انشطة المنظمات السياسية" },
        new ActivityType { Code = "9499", EnglishDescription = "Activities of other membership organizations not classified elsewhere", ArabicDescription = "انشطة المنظمات الاخرى ذات العضوية غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "9511", EnglishDescription = "Computer repair and accessories", ArabicDescription = "اصلاح الحاسبات الالية ومستلزماتها" },
        new ActivityType { Code = "9512", EnglishDescription = "Communication equipment repair", ArabicDescription = "اصلاح اجهزة الاتصالات" },
        new ActivityType { Code = "9521", EnglishDescription = "Electronic devices repair", ArabicDescription = "اصلاح الاجهزة الاليكترونية" },
        new ActivityType { Code = "9522", EnglishDescription = "Repair of tools, household appliances, and garden care equipment", ArabicDescription = "اصلاح الادوات والاجهزة المنزلية ومعدات العناية بالحدائق" },
        new ActivityType { Code = "9529", EnglishDescription = "Repair of other durable goods not classified elsewhere", ArabicDescription = "اصلاح السلع دائمة الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "9601", EnglishDescription = "Laundry activities", ArabicDescription = "انشطة الغسيل" },
        new ActivityType { Code = "9602", EnglishDescription = "Hairdressing and beauty salon", ArabicDescription = "تصفيف الشعر وصالون التجميل" },
        new ActivityType { Code = "9603", EnglishDescription = "Funeral and related activities", ArabicDescription = "الجنازة والانشطة ذات الصلة" },
        new ActivityType { Code = "9609", EnglishDescription = "Other personal services not classified elsewhere", ArabicDescription = "الخدمات الشخصية الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "9700", EnglishDescription = "Activities for households as employers of domestic workers", ArabicDescription = "انشطة الاسر كاصحاب عمال المنازل" },
        new ActivityType { Code = "9810", EnglishDescription = "Activities of households as producers of goods and services for own use", ArabicDescription = "انشطة الاسر كمنتجة للسلع والخدمات للاستخدام الشخصى" },
        new ActivityType { Code = "9820", EnglishDescription = "Undeclared activities of private households for own use", ArabicDescription = "الانشطة غير المعلنة للاسر الخاصة للاستخدام الشخصى" },
        new ActivityType { Code = "9900", EnglishDescription = "Extraterritorial organizations and entities", ArabicDescription = "المنظمات والكيانات الخارجية" },
        new ActivityType { Code = "9602", EnglishDescription = "Hair styling and other cosmetics", ArabicDescription = "تصفيف الشعر وانواع التجميل الاخرى" },
        new ActivityType { Code = "9603", EnglishDescription = "Funeral and related activities", ArabicDescription = "انشطة الجنائز وما يتصل بها" },
        new ActivityType { Code = "9609", EnglishDescription = "Other personal services activities not classified elsewhere", ArabicDescription = "انشطة الخدمات الشخصية الاخرى غير المصنفة فى مواضع اخرى" },
        new ActivityType { Code = "9700", EnglishDescription = "Home employment activities", ArabicDescription = "انشطة توظيف العمالة المنزلية" },
        new ActivityType { Code = "9810", EnglishDescription = "Activities of producing unearthed products and services for home appliances for personal use", ArabicDescription = "انشطة انتاج المنتجات والخدمات غير المتميزة الخاصة بالاجهزة المنزلية للاستخدام الشخصى" },
        new ActivityType { Code = "9820", EnglishDescription = "Activities of producing unearthed products and services for home appliances for personal use", ArabicDescription = "انشطة انتاج المنتجات والخدمات غير المتميزة الخاصة بالاجهزة المنزلية للاستخدام الشخصى" },
        new ActivityType { Code = "9900", EnglishDescription = "Activities of non-regional organizations and bodies", ArabicDescription = "انشطة المنظمات والهيئات غير الاقليمية" }


    };

        public static IEnumerable<ActivityType> GetAll()
        {
            return Codes;
        }

        public static ActivityType GetByCode(string code)
        {
            return Codes.FirstOrDefault(a => a.Code.Equals(code, StringComparison.InvariantCultureIgnoreCase));
        }
        public static ActivityType GetByEnglishDescription(string description)
        {
            return Codes.FirstOrDefault(a => a.EnglishDescription.Equals(description, StringComparison.InvariantCultureIgnoreCase));
        }

        public static ActivityType GetByArabicDescription(string description)
        {
            return Codes.FirstOrDefault(a => a.ArabicDescription.Equals(description, StringComparison.InvariantCultureIgnoreCase));
        }
    }
    public class ActivityType
    {
        public string Code { get; set; }
        public string EnglishDescription { get; set; }
        public string ArabicDescription { get; set; }
    }
}
