using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EgyptianeInvoicing.Core.Constants
{
    public static class CountryCodes
    {
        public static List<Country> Codes { get; } = new List<Country>
        {
            new Country("AD", "Andorra", "أندورا"),
            new Country("AE", "United Arab Emirates", "الامارات العربية المتحدة"),
            new Country("AF", "Afghanistan", "أفغانستان"),
            new Country("AG", "Antigua and Barbuda", "أنتيغوا وباربودا"),
            new Country("AI", "Anguilla", "أنجويلا"),
            new Country("AL", "Albania", "ألبانيا"),
            new Country("AM", "Armenia", "أرمينيا"),
            new Country("AO", "Angola", "أنجولا"),
            new Country("AQ", "Antarctica", "القارة القطبية الجنوبية"),
            new Country("AR", "Argentina", "الأرجنتين"),
            new Country("AS", "American Samoa", "ساموا الأمريكية"),
            new Country("AT", "Austria", "النمسا"),
            new Country("AU", "Australia", "أستراليا"),
            new Country("AW", "Aruba", "آروبا"),
            new Country("AX", "Åland Islands", "جزر أولان"),
            new Country("AZ", "Azerbaijan", "أذربيجان"),
            new Country("BA", "Bosnia and Herzegovina", "البوسنة والهرسك"),
            new Country("BB", "Barbados", "بربادوس"),
            new Country("BD", "Bangladesh", "بنجلاديش"),
            new Country("BE", "Belgium", "بلجيكا"),
            new Country("BF", "Burkina Faso", "بوركينا فاسو"),
            new Country("BG", "Bulgaria", "بلغاريا"),
            new Country("BH", "Bahrain", "البحرين"),
            new Country("BI", "Burundi", "بوروندي"),
            new Country("BJ", "Benin", "بنين"),
            new Country("BL", "Saint Barthelemy", "سان بارتيلمي"),
            new Country("BM", "Bermuda", "برمودا"),
            new Country("BN", "Brunei Darussalam", "بروناي"),
            new Country("BO", "Bolivia (Plurinational State of)", "بوليفيا"),
            new Country("BQ", "Bonaire, Sint Eustatius and Saba", "الجزر الكاريبية الهولندية"),
            new Country("BR", "Brazil", "البرازيل"),
            new Country("BS", "Bahamas", "الباهاما"),
            new Country("BT", "Bhutan", "بوتان"),
            new Country("BV", "Bouvet Island", "جزيرة بوفيه"),
            new Country("BW", "Botswana", "بتسوانا"),
            new Country("BY", "Belarus", "روسيا البيضاء"),
            new Country("BZ", "Belize", "بليز"),
            new Country("CA", "Canada", "كندا"),
            new Country("CC", "Cocos (Keeling) Islands", "جزر كوكوس"),
            new Country("CD", "Congo (Democratic Republic of the)", "جمهورية الكونغو الديمقراطية"),
            new Country("CF", "Central African Republic", "جمهورية أفريقيا الوسطى"),
            new Country("CG", "Congo", "جمهورية الكونغو"),
            new Country("CH", "Switzerland", "سويسرا"),
            new Country("CI", "Cote d’Ivoire", "ساحل العاج"),
            new Country("CK", "Cook Islands", "جزر كوك"),
            new Country("CL", "Chile", "شيلي"),
            new Country("CM", "Cameroon", "الكاميرون"),
            new Country("CN", "China", "الصين"),
            new Country("CO", "Colombia", "كولومبيا"),
            new Country("CR", "Costa Rica", "كوستاريكا"),
            new Country("CU", "Cuba", "كوبا"),
            new Country("CV", "Cabo Verde", "الرأس الأخضر"),
            new Country("CW", "Curaçao", "كوراساو"),
            new Country("CX", "Christmas Island", "جزيرة عيد الميلاد"),
            new Country("CY", "Cyprus", "قبرص"),
            new Country("CZ", "Czechia", "جمهورية التشيك"),
            new Country("DE", "Germany", "ألمانيا"),
            new Country("DJ", "Djibouti", "جيبوتي"),
            new Country("DK", "Denmark", "الدانمرك"),
            new Country("DM", "Dominica", "دومينيكا"),
            new Country("DO", "Dominican Republic", "جمهورية الدومينيكان"),
            new Country("DZ", "Algeria", "الجزائر"),
            new Country("EC", "Ecuador", "الاكوادور"),
            new Country("EE", "Estonia", "استونيا"),
            new Country("EG", "Egypt", "مصر"),
            new Country("EH", "Western Sahara", "الصحراء الغربية"),
            new Country("ER", "Eritrea", "اريتريا"),
            new Country("ES", "Spain", "أسبانيا"),
            new Country("ET", "Ethiopia", "اثيوبيا"),
            new Country("FI", "Finland", "فنلندا"),
            new Country("FJ", "Fiji", "فيجي"),
            new Country("FK", "Falkland Islands (Malvinas)", "جزر فوكلاند"),
            new Country("FM", "Micronesia (Federated States of)", "ميكرونيزيا"),
            new Country("FO", "Faroe Islands", "جزر فارو"),
            new Country("FR", "France", "فرنسا"),
            new Country("GA", "Gabon", "الجابون"),
            new Country("GB", "United Kingdom of Great Britain and Northern Ireland", "المملكة المتحدة"),
            new Country("GD", "Grenada", "جرينادا"),
            new Country("GE", "Georgia", "جورجيا"),
            new Country("GF", "French Guiana", "غويانا"),
            new Country("GG", "Guernsey", "جيرنزي"),
            new Country("GH", "Ghana", "غانا"),
            new Country("GI", "Gibraltar", "جبل طارق"),
            new Country("GL", "Greenland", "جرينلاند"),
            new Country("GM", "Gambia", "غامبيا"),
            new Country("GN", "Guinea", "غينيا"),
            new Country("GP", "Guadeloupe", "جوادلوب"),
            new Country("GQ", "Equatorial Guinea", "غينيا الاستوائية"),
            new Country("GR", "Greece", "اليونان"),
            new Country("GS", "South Georgia and the South Sandwich Islands", "جورجيا الجنوبية وجزر ساندويتش الجنوبية"),
            new Country("GT", "Guatemala", "جواتيمالا"),
            new Country("GU", "Guam", "جوام"),
            new Country("GW", "Guinea-Bissau", "غينيا بيساو"),
            new Country("GY", "Guyana", "غيانا"),
            new Country("HK", "Hong Kong", "هونغ كونغ"),
            new Country("HM", "Heard Island and McDonald Islands", "جزيرة هيرد وجزر ماكدونالد"),
            new Country("HN", "Honduras", "هندوراس"),
            new Country("HR", "Croatia", "كرواتيا"),
            new Country("HT", "Haiti", "هايتي"),
            new Country("HU", "Hungary", "المجر"),
            new Country("ID", "Indonesia", "اندونيسيا"),
            new Country("IE", "Ireland", "أيرلندا"),
            new Country("IL", "Israel", "اسرائيل"),
            new Country("IM", "Isle of Man", "جزيرة مان"),
            new Country("IN", "India", "الهند"),
            new Country("IO", "British Indian Ocean Territory", "إقليم المحيط الهندي البريطاني"),
            new Country("IQ", "Iraq", "العراق"),
            new Country("IR", "Iran (Islamic Republic of)", "ايران"),
            new Country("IS", "Iceland", "أيسلندا"),
            new Country("IT", "Italy", "ايطاليا"),
            new Country("JE", "Jersey", "جيرسي"),
            new Country("JM", "Jamaica", "جامايكا"),
            new Country("JO", "Jordan", "الأردن"),
            new Country("JP", "Japan", "اليابان"),
            new Country("KE", "Kenya", "كينيا"),
            new Country("KG", "Kyrgyzstan", "قرغيزستان"),
            new Country("KH", "Cambodia", "كمبوديا"),
            new Country("KI", "Kiribati", "كيريباتي"),
            new Country("KM", "Comoros", "جزر القمر"),
            new Country("KN", "Saint Kitts and Nevis", "سانت كيتس ونيفيس"),
            new Country("KP", "Korea (Democratic People’s Republic of)", "كوريا الشمالية"),
            new Country("KR", "Korea (Republic of)", "كوريا الجنوبية"),
            new Country("KW", "Kuwait", "الكويت"),
            new Country("KY", "Cayman Islands", "جزر كايمان"),
            new Country("KZ", "Kazakhstan", "كازاخستان"),
            new Country("LA", "Lao People’s Democratic Republic", "لاوس"),
            new Country("LB", "Lebanon", "لبنان"),
            new Country("LC", "Saint Lucia", "سانت لوسيا"),
            new Country("LI", "Liechtenstein", "ليختنشتاين"),
            new Country("LK", "Sri Lanka", "سريلانكا"),
            new Country("LR", "Liberia", "ليبيريا"),
            new Country("LS", "Lesotho", "ليسوتو"),
            new Country("LT", "Lithuania", "ليتوانيا"),
            new Country("LU", "Luxembourg", "لوكسمبورج"),
            new Country("LV", "Latvia", "لاتفيا"),
            new Country("LY", "Libya", "ليبيا"),
            new Country("MA", "Morocco", "المغرب"),
            new Country("MC", "Monaco", "موناكو"),
            new Country("MD", "Moldova (Republic of)", "مولدافيا"),
            new Country("ME", "Montenegro", "الجبل الأسود"),
            new Country("MF", "Saint Martin (French Part)", "تجمع سان مارتين"),
            new Country("MG", "Madagascar", "مدغشقر"),
            new Country("MH", "Marshall Islands", "جزر مارشال"),
            new Country("MK", "North Macedonia", "مقدونيا"),
            new Country("ML", "Mali", "مالي"),
            new Country("MM", "Myanmar", "ميانمار"),
            new Country("MN", "Mongolia", "منغوليا"),
            new Country("MO", "Macao", "ماكاو"),
            new Country("MP", "Northern Mariana Islands", "جزر ماريانا الشمالية"),
            new Country("MQ", "Martinique", "مارتينيك"),
            new Country("MR", "Mauritania", "موريتانيا"),
            new Country("MS", "Montserrat", "مونتسرات"),
            new Country("MT", "Malta", "مالطا"),
            new Country("MU", "Mauritius", "موريشيوس"),
            new Country("MV", "Maldives", "جزر المالديف"),
            new Country("MW", "Malawi", "ملاوي"),
            new Country("MX", "Mexico", "المكسيك"),
            new Country("MY", "Malaysia", "ماليزيا"),
            new Country("MZ", "Mozambique", "موزمبيق"),
            new Country("NA", "Namibia", "ناميبيا"),
            new Country("NC", "New Caledonia", "كاليدونيا الجديدة"),
            new Country("NE", "Niger", "النيجر"),
            new Country("NF", "Norfolk Island", "جزيرة نورفولك"),
            new Country("NG", "Nigeria", "نيجيريا"),
            new Country("NI", "Nicaragua", "نيكاراجوا"),
            new Country("NL", "Netherlands", "هولندا"),
            new Country("NO", "Norway", "النرويج"),
            new Country("NP", "Nepal", "نيبال"),
            new Country("NR", "Nauru", "نورو"),
            new Country("NU", "Niue", "نيوي"),
            new Country("NZ", "New Zealand", "نيوزيلاندا"),
            new Country("OM", "Oman", "عمان"),
            new Country("PA", "Panama", "بنما"),
            new Country("PE", "Peru", "بيرو"),
            new Country("PF", "French Polynesia", "بولينزيا الفرنسية"),
            new Country("PG", "Papua New Guinea", "بابوا غينيا الجديدة"),
            new Country("PH", "Philippines", "الفيلبين"),
            new Country("PK", "Pakistan", "باكستان"),
            new Country("PL", "Poland", "بولندا"),
            new Country("PM", "Saint Pierre and Miquelon", "سان بيير وميكلون"),
            new Country("PN", "Pitcairn", "بتكايرن"),
            new Country("PR", "Puerto Rico", "بورتوريكو"),
            new Country("PS", "Palestinian, State of", "فلسطين"),
            new Country("PT", "Portugal", "البرتغال"),
            new Country("PW", "Palau", "بالاو"),
            new Country("PY", "Paraguay", "باراجواي"),
            new Country("QA", "Qatar", "قطر"),
            new Country("RE", "Réunion", "روينيون"),
            new Country("RO", "Romania", "رومانيا"),
            new Country("RS", "Serbia", "صربيا"),
            new Country("RU", "Russian Federation", "روسيا"),
            new Country("RW", "Rwanda", "رواندا"),
            new Country("SA", "Saudi Arabia", "السعودية"),
            new Country("SB", "Solomon Islands", "جزر سليمان"),
            new Country("SC", "Seychelles", "سيشل"),
            new Country("SD", "Sudan", "السودان"),
            new Country("SE", "Sweden", "السويد"),
            new Country("SG", "Singapore", "سنغافورة"),
            new Country("SH", "Saint Helena, Ascension and Tristan da Cunha", "سانت هيلينا وأسينشين وتريستان دا كونا"),
            new Country("SI", "Slovenia", "سلوفينيا"),
            new Country("SJ", "Svalbard and Jan Mayen", "سفالبارد ويان ماين"),
            new Country("SK", "Slovakia", "سلوفاكيا"),
            new Country("SL", "Sierra Leone", "سيراليون"),
            new Country("SM", "San Marino", "سان مارينو"),
            new Country("SN", "Senegal", "السنغال"),
            new Country("SO", "Somalia", "الصومال"),
            new Country("SR", "Suriname", "سورينام"),
            new Country("SS", "South Sudan", "جنوب السودان"),
            new Country("ST", "Sao Tome and Principe", "ساو تومي وبرينسيب"),
            new Country("SV", "El Salvador", "السلفادور"),
            new Country("SX", "Sint Maarten (Dutch Part)", "سينت مارتن"),
            new Country("SY", "Syrian Arab Republic", "سوريا"),
            new Country("SZ", "Eswatini", "سوازيلاند"),
            new Country("TC", "Turks and Caicos Islands", "جزر توركس وكايكوس"),
            new Country("TD", "Chad", "تشاد"),
            new Country("TF", "French Southern Territories", "أراض فرنسية جنوبية وأنتارتيكية"),
            new Country("TG", "Togo", "توجو"),
            new Country("TH", "Thailand", "تايلند"),
            new Country("TJ", "Tajikistan", "طاجكستان"),
            new Country("TK", "Tokelau", "توكيلو"),
            new Country("TL", "Timor-Leste", "تيمور الشرقية"),
            new Country("TM", "Turkmenistan", "تركمانستان"),
            new Country("TN", "Tunisia", "تونس"),
            new Country("TO", "Tonga", "تونجا"),
            new Country("TR", "Turkey", "تركيا"),
            new Country("TT", "Trinidad and Tobago", "ترينيداد وتوباغو"),
            new Country("TV", "Tuvalu", "توفالو"),
            new Country("TW", "Taiwan (Province of China)", "تايوان"),
            new Country("TZ", "Tanzania, United Republic of", "تانزانيا"),
            new Country("UA", "Ukraine", "أوكرانيا"),
            new Country("UG", "Uganda", "أوغندا"),
            new Country("UM", "United States Minor Outlying Islands", "جزر الولايات المتحدة الصغيرة النائية"),
            new Country("US", "United States of America", "الولايات المتحدة"),
            new Country("UY", "Uruguay", "أورجواي"),
            new Country("UZ", "Uzbekistan", "أوزبكستان"),
            new Country("VA", "Holy See", "الفاتيكان"),
            new Country("VC", "Saint Vincent and the Grenadines", "سانت فينسنت والغرينادين"),
            new Country("VE", "Venezuela (Bolivarian Republic of)", "فنزويلا"),
            new Country("VG", "Virgin Islands (British)", "جزر العذراء البريطانية"),
            new Country("VI", "Virgin Islands (U.S.)", "جزر العذراء الأمريكية"),
            new Country("VN", "Viet Nam", "فيتنام"),
            new Country("VU", "Vanuatu", "فانواتو"),
            new Country("WF", "Wallis and Futuna", "والس وفوتونا"),
            new Country("WS", "Samoa", "ساموا"),
            new Country("YE", "Yemen", "اليمن"),
            new Country("YT", "Mayotte", "مايوت"),
            new Country("ZA", "South Africa", "جنوب أفريقيا"),
            new Country("ZM", "Zambia", "زامبيا"),
            new Country("ZW", "Zimbabwe", "زيمبابوي")
        };

        public static IEnumerable<Country> GetAll()
        {
            return Codes;
        }

        public static Country GetByCode(string code)
        {
            return Codes.FirstOrDefault(c => c.Code.Equals(code, StringComparison.InvariantCultureIgnoreCase));
        }
        public static Country GetByEnglishDescription(string description)
        {
            return Codes.FirstOrDefault(a => a.EnglishDescription.Equals(description, StringComparison.InvariantCultureIgnoreCase));
        }

        public static Country GetByArabicDescription(string description)
        {
            return Codes.FirstOrDefault(a => a.ArabicDescription.Equals(description, StringComparison.InvariantCultureIgnoreCase));
        }
    }
    public class Country
    {
        public string Code { get; }
        public string EnglishDescription { get; }
        public string ArabicDescription { get; }

        public Country(string code, string nameEnglish, string nameArabic)
        {
            Code = code;
            EnglishDescription = nameEnglish;
            ArabicDescription = nameArabic;
        }
    }

}
